language: ruby
git:
  depth: false
cache: bundler
before_install:
- bundle install
script: bundle exec rake book:build
after_success: 
- script/tag_on_master
before_deploy: bundle install && bundle exec rake book:build
deploy:
  provider: releases
  file_glob: true
  file:
  - progit*.epub
  - progit*.mobi
  - progit*.pdf
  skip_cleanup: true
  on:
    tags: true
  api-key: $GITHUB_API_TOKEN
branches:
  only:
  - master
  - /^2\.1(\.\d+)+$/

addons:
  apt:
    packages:
      - epubcheck
notifications:
  email:
    on_success: never
    on_failure: always
